name: GHAS Billing Export
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5 * * 2'


jobs:
  get-billers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Get billers
        run: |
          # execute python script
          python get-billers.py 
        env:
          API_ENDPOINT: "api.github.com"
          ENTERPRISE_NAME: "burrito-party"
          ADMIN_TOKEN: ${{ secrets.ENT_ADMIN_TOKEN }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: GHAS-committers.json
          path: GHAS-committers.json
