name: GHAS Billing Export
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5 * * 2'


jobs:
  get-billers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install requests
      
      - name: Get billers
        run: |
          # Set issue number as env variable
          WORKING_REPO=${{ github.event.repository.full_name }}
          ISSUE_NUM=${{ github.event.issue.number }}

          # execute python script
          python get-billers.py 

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADMIN_TOKEN: ${{ secrets.ENT_ADMIN_TOKEN }}
          GH_TOKEN: ${{ secrets.ENT_ADMIN_TOKEN }}
